### ISSUE TITLE
Jena version is still at v. 3

### ISSUE THREAD

**Issue by ericdscott** [ont-app/igraph-jena#3]
Jena has a version 4 out. It will break under java 8 and seems to require at least java 11.

Simple upgrade to the project dependencies yields this error:

```
 "Syntax error (NoSuchFieldException) compiling . at (ont_app/igraph_jena/core_test.clj:45:9).\ncreateMem\n",
```

**Comment by ont-app** [comment]
Fixed as of v. 0.2
